services:
  rtsp-server:
    image: bluenviron/mediamtx #aler9/rtsp-simple-server
    container_name: rtsp-server
    ports:
      - "8554:8554"
      - "1935:1935"
      - "8888:8888"
    volumes:
      - ./rtsp-simple-server.yml:/rtsp-simple-server.yml

  camera1:
    image: jrottenberg/ffmpeg
    command: >
      -re -stream_loop -1
      -i /data/sample_1080p_h264.mp4
      -map 0:v:0
      -c:v libx264
      -f rtsp
      rtsp://rtsp-server:8554/camera1
    depends_on:
      - rtsp-server
    volumes:
      - ./:/data

  camera2:
    image: jrottenberg/ffmpeg
    command: >
      -re -stream_loop -1
      -i /data/sample_1080p_h264.mp4
      -map 0:v:0
      -c:v libx264
      -f rtsp
      rtsp://rtsp-server:8554/camera2
    depends_on:
      - rtsp-server
    volumes:
      - ./:/data
